Tech debt/enumerate in request join trip
jncaceres/Carpou pull request #39
Opened 2022-06-15 21:35 UTC by burgosibarra

- Enumerate fue usado en la creación de solicitud de viaje.
- Se modifica la condición para crear solicitud. Ahora solo se puede crear una solicitud si el número de solicitudes ya aceptadas es menor a la cantidad de asientos ofrecidos en el viaje (antes se podía si el numero de solicitudes sin importar su estado era menor a la cantidad de asientos ofrecidos en el viaje)
- Los test fallan por el TripController, este archivo no fue modificado en esta PR, queda pendiente la actualización  de esta rama cuando se solucione dicho problema

2022-06-17 23:34 UTC, bceppi requested changes
Ojo que el PR tiene varias cosas más que la descripción, tratar de hacerlos más acotados

2022-06-17 23:34 UTC, bceppi commented on app/controllers/passenger_requests_controller.rb
>      already_requested = previous_request.find_by(user_id: current_user.id)
```suggestion
    # Look if the user has already requested to join
    already_requested = PassengerRequest.find_by(trip_id: trip_id, user_id: current_user.id)
```

2022-06-17 23:34 UTC, bceppi commented on app/controllers/passenger_requests_controller.rb
> +    # if not
```suggestion
```

2022-06-17 23:34 UTC, bceppi commented on app/controllers/passenger_requests_controller.rb
> +    # if not
Pocos comentarios not good, too much neither

2022-06-17 23:34 UTC, bceppi commented on app/views/layouts/application.html.erb
> +          my_requests_route: passenger_requests_from_user_path(current_user.id),
Esta forma de manejar las rutas la deprecamos, deberíamos manejarlas desde front

2022-06-18 01:33 UTC, jncaceres commented
Concuerdo con los comentarios de @bceppi

2022-06-18 19:57 UTC, burgosibarra commented on app/views/layouts/application.html.erb
> +          my_requests_route: passenger_requests_from_user_path(current_user.id),
se corrigen todas las rutas tratadas en dicho archivo y en Header, de esta manera todas las rutas quedan en app/javascript/api

2022-06-19 02:20 UTC, jncaceres approved these changes

2022-06-20 05:33 UTC, merged