Fix/set models
jncaceres/Carpou pull request #42
Opened 2022-06-17 15:20 UTC by burgosibarra

2022-06-17 23:45 UTC, bceppi requested changes

2022-06-17 23:45 UTC, bceppi commented on app/controllers/places_controller.rb
> +    end
```suggestion
    @place = Place.find_by(id: params[:id])
    if @place.nil?
      redirect_to(root_path, alert: 'No existe el lugar pedido')
    end
```

2022-06-17 23:45 UTC, bceppi commented on app/controllers/passenger_requests_controller.rb
> +    end
```suggestion
    @passenger_request = PassengerRequest.find_by(id: params[:id])
    if @passenger_request.nil?
      # TODO: Queda pendiente reemplazar el siguiente redirect por el comentado
      # cuando se haga merge de la rama feat/passenger-request-view
      redirect_to(root_path, alert: 'No existe la solicitud pedida')
      # redirect_to(passenger_requests_from_user_path(id: current_user.id), alert: 'No existe la solicitud pedida')
    end
```

2022-06-17 23:45 UTC, bceppi commented on app/controllers/trips_controller.rb
> +    @trip = Trip.where(id: params[:id])
Hacer el mismo cambio sugerido anteriormente, aca también. Where por find_by

2022-06-17 23:45 UTC, bceppi commented on spec/controllers/trips/show_unit_spec.rb
> +      id = (0...8).map { rand(48..90).chr }.join
```suggestion
      id = SecureRandom.hex(4)
```

2022-06-17 23:52 UTC, bceppi commented
No olvidar agregar descripción al PR

2022-06-18 19:15 UTC, burgosibarra commented on app/controllers/places_controller.rb
> +    end
Se considera el comentario, pero se deja de la siguiente manera por linters:
def set_place
    @place = Place.find_by(id: params[:id])
    redirect_to(root_path, alert: 'No existe el lugar pedido') if @place.nil?
  end

2022-06-18 19:15 UTC, burgosibarra commented on app/controllers/places_controller.rb
> +    end
Lo mismo ocurre en los siguientes

2022-06-18 19:15 UTC, burgosibarra commented on spec/controllers/trips/show_unit_spec.rb
> +      id = (0...8).map { rand(48..90).chr }.join
Se realiza el cambio sugerido

2022-06-18 19:16 UTC, burgosibarra commented
Los cambios sugeridos fueron incluidos

2022-06-19 02:23 UTC, jncaceres requested changes

2022-06-19 02:23 UTC, jncaceres commented on app/controllers/passenger_requests_controller.rb
> +    redirect_to(root_path, alert: 'No existe el lugar pedido') if @passenger_request.nil?
Debería ser 'No existe la solicitud pedida' o no?

2022-06-19 03:34 UTC, burgosibarra commented on app/controllers/passenger_requests_controller.rb
> +    redirect_to(root_path, alert: 'No existe el lugar pedido') if @passenger_request.nil?
listo

2022-06-19 03:35 UTC, jncaceres approved these changes

2022-06-20 05:38 UTC, merged