Feat/cancel a trip
jncaceres/Carpou pull request #43
Opened 2022-06-17 17:49 UTC by burgosibarra

2022-06-17 23:51 UTC, bceppi requested changes

2022-06-17 23:51 UTC, bceppi commented on app/controllers/trips_controller.rb
> +      request.destroy
Esta lógica debería trabajarse a nivel de modelo y no de controlador.. hay una forma de hacerlo así y que también queda más ordenado.

2022-06-17 23:51 UTC, bceppi commented on config/environments/production.rb
> +  config.action_mailer.preview_path = "#{Rails.root}/test/mailers/previews"
En teoría, en prod no debería ir

2022-06-17 23:52 UTC, bceppi commented
Súper bien los tests, en general observo que metes mucha lógica en los controladores, cuando solo deberían encargarse de "orquestar" más que encargarse de "ejecutar". La ejecución debería ocurrir a nivel de modelo.

2022-06-18 20:37 UTC, burgosibarra commented on app/controllers/trips_controller.rb
> +      request.destroy
corregido

2022-06-18 20:39 UTC, burgosibarra commented on config/environments/production.rb
> +  config.action_mailer.preview_path = "#{Rails.root}/test/mailers/previews"
eliminado

2022-06-19 02:33 UTC, jncaceres reviewed
Creo que el mail no se esta enviando, al menos probé y en el mail de carpou no me sale en los mails enviados

2022-06-20 04:34 UTC, jncaceres approved these changes

2022-06-20 06:03 UTC, merged